package com.flippingfriend.companion;
import com.flippingfriend.model.FillCurve; import java.util.ArrayList; import java.util.Collections; import java.util.List;
/** Immutable shared fill authority and ordered generated-quantity inputs. */
final class BuyReplacementQuantityFillInputContext {
 private final BuyReplacementCandidateFillInputContext candidateFillInputContext; private final BuyReplacementQuantityGridCandidateSet source; private final List<BuyReplacementQuantityFillInput> inputs; private final FillCurve fillCurve; private final double effectiveHorizonHours; private final double seasonalMultiplier; private final long historyObservedAt; private final long marketContextObservedAt; private final long composedAt;
 BuyReplacementQuantityFillInputContext(BuyReplacementQuantityGridCandidateSet s,List<BuyReplacementQuantityFillInput> i,FillCurve f,double h,double season,long historyAt,long marketAt,long at){this(s,i,f,h,season,historyAt,marketAt,at,null);}
 // Legacy direct construction has no retained metadata provenance.
 BuyReplacementQuantityFillInputContext(BuyReplacementQuantityGridCandidateSet s,List<BuyReplacementQuantityFillInput> i,FillCurve f,double h,double season,long historyAt,long marketAt,long at,BuyReplacementCandidateFillInputContext original){source=s;inputs=Collections.unmodifiableList(new ArrayList<>(i));fillCurve=f;effectiveHorizonHours=h;seasonalMultiplier=season;historyObservedAt=historyAt;marketContextObservedAt=marketAt;composedAt=at;candidateFillInputContext=original;}
 BuyReplacementCandidateFillInputContext getCandidateFillInputContext(){return candidateFillInputContext;}
 String getIntentId(){return source.getIntentId();} String getOriginalOfferIdentity(){return source.getOriginalOfferIdentity();} String getRecommendationId(){return source.getRecommendationId();} int getItemId(){return source.getItemId();} int getExactRemainderQuantity(){return source.getExactRemainderQuantity();} String getAppetiteName(){return source.getAppetiteName();} List<BuyReplacementQuantityGridCandidate> getCandidates(){return source.getCandidates();} List<BuyReplacementQuantityFillInput> getInputs(){return inputs;} FillCurve getFillCurve(){return fillCurve;} double getEffectiveHorizonHours(){return effectiveHorizonHours;} double getSeasonalMultiplier(){return seasonalMultiplier;} long getHistoryObservedAt(){return historyObservedAt;} long getMarketContextObservedAt(){return marketContextObservedAt;} long getQuantityGridComposedAt(){return source.getComposedAt();} long getComposedAt(){return composedAt;}
}
