package com.flippingfriend.companion;
import java.util.List;
/** Immutable binding of quantity-specific completion evidence to one effective wait multiplier. */
final class BuyReplacementQuantityDurationCalibrationInputContext {
 private final BuyReplacementQuantityRoundTripCompletionEvaluationSet source; private final boolean learningDisabled; private final double waitMultiplier; private final long composedAt;
 BuyReplacementQuantityDurationCalibrationInputContext(BuyReplacementQuantityRoundTripCompletionEvaluationSet s,boolean d,double m,long at){source=s;learningDisabled=d;waitMultiplier=m;composedAt=at;}
 BuyReplacementQuantityRoundTripCompletionEvaluationSet getSource(){return source;}
 String getIntentId(){return source.getIntentId();} String getOriginalOfferIdentity(){return source.getOriginalOfferIdentity();} String getRecommendationId(){return source.getRecommendationId();} int getItemId(){return source.getItemId();} int getExactRemainderQuantity(){return source.getExactRemainderQuantity();} String getAppetiteName(){return source.getAppetiteName();} double getEffectiveHorizonHours(){return source.getEffectiveHorizonHours();} double getSeasonalMultiplier(){return source.getSeasonalMultiplier();} long getHistoryObservedAt(){return source.getHistoryObservedAt();} long getMarketContextObservedAt(){return source.getMarketContextObservedAt();} long getFillInputComposedAt(){return source.getFillInputComposedAt();} long getFillEvaluatedAt(){return source.getFillEvaluatedAt();} long getFillViabilityAssessedAt(){return source.getFillViabilityAssessedAt();} long getRoundTripCompletionEvaluatedAt(){return source.getEvaluatedAt();} List<BuyReplacementQuantityFillEvaluation> getCompleteFillEvaluations(){return source.getCompleteFillEvaluations();} List<BuyReplacementQuantityFillViableCandidate> getViableCandidates(){return source.getViableCandidates();} List<BuyReplacementQuantityRoundTripCompletionEvaluation> getEvaluations(){return source.getEvaluations();} boolean isLearningDisabled(){return learningDisabled;} double getWaitMultiplier(){return waitMultiplier;} long getComposedAt(){return composedAt;}
}
