package com.flippingfriend.companion;
import com.flippingfriend.model.TaxCalculator; import java.util.ArrayList; import java.util.List;
/** Pure fail-closed application of CandidateFactory unwindCost arithmetic. */
final class BuyReplacementUnwindLossEvaluator {
 private static final double MIN_DRIFT_FRACTION=0.002; private static final double ADVERSE_DRIFT_SHARE=0.25; private static final double MAX_USABLE_VOLATILITY=0.2; private final TaxCalculator tax;
 BuyReplacementUnwindLossEvaluator(TaxCalculator t){tax=t;}
 BuyReplacementUnwindLossEvaluationSet evaluate(BuyReplacementUnwindLossInputContext s,long at){if(s==null||tax==null||at<s.getComposedAt()||s.getComposedAt()+CompanionBuyReplacementReadinessPolicy.MAX_INPUT_AGE_SECONDS<at||s.getEvaluations()==null||s.getEvaluations().isEmpty()||s.getCurrentLowPrice()<=0||s.getBucketSeconds()<=0||!Double.isFinite(s.getVolatility())||s.getVolatility()<0||!Double.isFinite(s.getEffectiveHorizonHours())||s.getEffectiveHorizonHours()<=0)return null;double bucketsPerHour=3600.0/Math.max(1,s.getBucketSeconds());double buckets=Math.max(1.0,s.getEffectiveHorizonHours()*bucketsPerHour);double sigma=Math.min(MAX_USABLE_VOLATILITY,s.getVolatility())*Math.sqrt(buckets);double drift=Math.max(MIN_DRIFT_FRACTION,ADVERSE_DRIFT_SHARE*sigma);if(!Double.isFinite(drift)||drift<MIN_DRIFT_FRACTION)return null;List<BuyReplacementUnwindLossEvaluation> out=new ArrayList<>(s.getEvaluations().size());for(BuyReplacementExpectedSlotOccupancyEvaluation e:s.getEvaluations()){if(!valid(e,s))return null;int exitPrice=Math.max(1,(int)Math.round(Math.min(e.getBuyPrice(),s.getCurrentLowPrice())*(1-drift)));int exitTax=tax.taxPerItem(s.getItemId(),exitPrice);long proceeds=(long)exitPrice-exitTax;long loss=Math.max(0,(long)e.getBuyPrice()-proceeds);long total=loss*e.getExactRemainderQuantity();if(total<0)return null;out.add(new BuyReplacementUnwindLossEvaluation(e,drift,exitPrice,exitTax,loss,total));}return new BuyReplacementUnwindLossEvaluationSet(s,out,at);}
 private static boolean valid(BuyReplacementExpectedSlotOccupancyEvaluation e,BuyReplacementUnwindLossInputContext s){return e!=null&&e.getExactRemainderQuantity()==s.getExactRemainderQuantity()&&e.getBuyPrice()>0&&e.getSellPrice()>0&&e.getTotalCost()==(long)e.getBuyPrice()*e.getExactRemainderQuantity()&&Double.isFinite(e.getExpectedSlotHours())&&e.getExpectedSlotHours()>=1.0/60.0;}
}
