package com.flippingfriend.companion;
import com.flippingfriend.model.TaxCalculator; import java.util.ArrayList; import java.util.List;
/** Pure fail-closed positive-net-margin interpretation without ranking or selection. */
final class BuyReplacementNetMarginEligibilityEvaluator {
 BuyReplacementNetMarginEligibilityAssessment evaluate(BuyReplacementNetMarginEvaluationSet s,TaxCalculator tax,long at){
  if(s==null||tax==null||at<s.getEvaluatedAt()||s.getEvaluations()==null||s.getEvaluations().isEmpty()||s.getPositiveSpreadCandidates()==null||s.getEvaluations().size()!=s.getPositiveSpreadCandidates().size())return null;
  List<BuyReplacementNetMarginEvaluation> complete=new ArrayList<>(s.getEvaluations().size()); List<BuyReplacementPositiveNetMarginCandidate> positive=new ArrayList<>();
  for(int i=0;i<s.getEvaluations().size();i++){BuyReplacementNetMarginEvaluation e=s.getEvaluations().get(i);BuyReplacementPositiveSpreadCandidate c=s.getPositiveSpreadCandidates().get(i);if(!valid(e,c,s,tax))return null;complete.add(e);if(e.getNetMarginPerItem()>0)positive.add(new BuyReplacementPositiveNetMarginCandidate(e));}
  return new BuyReplacementNetMarginEligibilityAssessment(s,positive.isEmpty()?BuyReplacementNetMarginEligibilityOutcome.INELIGIBLE:BuyReplacementNetMarginEligibilityOutcome.ELIGIBLE,complete,positive,at);
 }
 private static boolean valid(BuyReplacementNetMarginEvaluation e,BuyReplacementPositiveSpreadCandidate c,BuyReplacementNetMarginEvaluationSet s,TaxCalculator tax){if(e==null||c==null||e.getBuyOffsetIndex()!=c.getBuyOffsetIndex()||Double.compare(e.getBuyOffset(),c.getBuyOffset())!=0||e.getBuyPrice()!=c.getBuyPrice()||e.getExactRemainderQuantity()!=s.getExactRemainderQuantity()||e.getExactRemainderQuantity()!=c.getExactRemainderQuantity()||e.getTotalCost()!=c.getTotalCost()||Double.compare(e.getBuyProbability(),c.getBuyProbability())!=0||Double.compare(e.getBuyExpectedHours(),c.getBuyExpectedHours())!=0||Double.compare(e.getBuyUnitsPerHour(),c.getBuyUnitsPerHour())!=0||Double.compare(e.getBuyWaitHours(),c.getBuyWaitHours())!=0||e.getSellOffsetIndex()!=c.getSellOffsetIndex()||Double.compare(e.getSellOffset(),c.getSellOffset())!=0||e.getSellPrice()!=c.getSellPrice()||e.getRawSpreadPerItem()!=c.getRawSpreadPerItem())return false;int t=tax.taxPerItem(s.getItemId(),e.getSellPrice());long m=tax.netMarginPerItem(s.getItemId(),e.getBuyPrice(),e.getSellPrice());long tt=tax.taxFor(s.getItemId(),e.getSellPrice(),e.getExactRemainderQuantity());long tm=tax.netProfit(s.getItemId(),e.getBuyPrice(),e.getSellPrice(),e.getExactRemainderQuantity());return e.getTaxPerItem()==t&&e.getNetMarginPerItem()==m&&e.getTotalTax()==tt&&e.getTotalNetMargin()==tm;}
}
