package com.flippingfriend.companion;
import com.flippingfriend.data.Candle; import com.flippingfriend.model.FillCurve; import java.util.ArrayList; import java.util.List;
/** Pure fail-closed history preparation without invoking the fill model. */
final class BuyReplacementSellFillInputContextComposer {
 BuyReplacementSellFillInputContext compose(BuyReplacementNetMarginEligibilityAssessment s,List<Candle> history,long observed,long at){
  if(s==null||s.getOutcome()!=BuyReplacementNetMarginEligibilityOutcome.ELIGIBLE||s.getPositiveNetMarginCandidates()==null||s.getPositiveNetMarginCandidates().isEmpty()||history==null||history.size()<2||observed<0||at<0||observed>at||s.getAssessedAt()>at||observed+CompanionBuyReplacementReadinessPolicy.MAX_INPUT_AGE_SECONDS<at||s.getAssessedAt()+CompanionBuyReplacementReadinessPolicy.MAX_INPUT_AGE_SECONDS<at||s.getExactRemainderQuantity()<=0||!Double.isFinite(s.getEffectiveHorizonHours())||s.getEffectiveHorizonHours()<=0)return null;
  List<BuyReplacementPositiveNetMarginCandidate> c=new ArrayList<>(s.getPositiveNetMarginCandidates().size()); for(BuyReplacementPositiveNetMarginCandidate v:s.getPositiveNetMarginCandidates()){if(!valid(v,s))return null;c.add(v);} List<Candle> copied=copy(history,observed);if(copied==null)return null;FillCurve curve=FillCurve.overRecentHistory(copied);if(curve.isEmpty())return null;return new BuyReplacementSellFillInputContext(s,c,curve,observed,at);
 }
 private static boolean valid(BuyReplacementPositiveNetMarginCandidate v,BuyReplacementNetMarginEligibilityAssessment s){return v!=null&&v.getBuyOffsetIndex()>=0&&Double.isFinite(v.getBuyOffset())&&v.getBuyPrice()>0&&v.getSellOffsetIndex()>=0&&Double.isFinite(v.getSellOffset())&&v.getSellPrice()>v.getBuyPrice()&&v.getExactRemainderQuantity()==s.getExactRemainderQuantity()&&v.getTotalCost()==(long)v.getBuyPrice()*s.getExactRemainderQuantity()&&v.getRawSpreadPerItem()==(long)v.getSellPrice()-v.getBuyPrice()&&v.getNetMarginPerItem()>0&&v.getTotalTax()==(long)v.getTaxPerItem()*v.getExactRemainderQuantity()&&v.getTotalNetMargin()==v.getNetMarginPerItem()*v.getExactRemainderQuantity()&&Double.isFinite(v.getBuyProbability())&&v.getBuyProbability()>0&&v.getBuyProbability()<=1&&Double.isFinite(v.getBuyExpectedHours())&&v.getBuyExpectedHours()>=0&&Double.isFinite(v.getBuyUnitsPerHour())&&v.getBuyUnitsPerHour()>=0&&!Double.isNaN(v.getBuyWaitHours())&&v.getBuyWaitHours()>=0;}
 private static List<Candle> copy(List<Candle> h,long observed){List<Candle> out=new ArrayList<>(h.size());long previous=-1;for(Candle x:h){if(x==null||x.getTimestamp()<0||x.getTimestamp()>observed||x.getTimestamp()<previous||x.getHighPriceVolume()<0||x.getLowPriceVolume()<0)return null;previous=x.getTimestamp();out.add(new Candle(x.getTimestamp(),x.getAvgHighPrice(),x.getAvgLowPrice(),x.getHighPriceVolume(),x.getLowPriceVolume()));}return out;}
}
