package com.flippingfriend.companion;
import com.flippingfriend.model.FillEstimate; import com.flippingfriend.model.FillModel; import java.util.ArrayList; import java.util.List;
/** Pure fail-closed measured sell-fill evaluation without filtering or choosing candidates. */
final class BuyReplacementSellFillEvaluator {
 private final FillModel fillModel; BuyReplacementSellFillEvaluator(FillModel f){fillModel=f;}
 BuyReplacementSellFillEvaluationSet evaluate(BuyReplacementSellFillInputContext s,long at){if(s==null||fillModel==null||at<s.getComposedAt()||s.getComposedAt()+CompanionBuyReplacementReadinessPolicy.MAX_INPUT_AGE_SECONDS<at||s.getFillCurve()==null||s.getFillCurve().isEmpty()||s.getCandidates()==null||s.getCandidates().isEmpty())return null;List<BuyReplacementSellFillEvaluation> out=new ArrayList<>(s.getCandidates().size());for(BuyReplacementPositiveNetMarginCandidate c:s.getCandidates()){if(!valid(c,s))return null;FillEstimate e=fillModel.estimateSell(s.getFillCurve(),c.getSellPrice(),c.getExactRemainderQuantity(),s.getEffectiveHorizonHours());if(!valid(e))return null;out.add(new BuyReplacementSellFillEvaluation(c,e.getProbability(),e.getExpectedHours(),e.getUnitsPerHour(),e.getWaitHours()));}return new BuyReplacementSellFillEvaluationSet(s,out,at);}
 private static boolean valid(BuyReplacementPositiveNetMarginCandidate c,BuyReplacementSellFillInputContext s){return c!=null&&c.getExactRemainderQuantity()==s.getExactRemainderQuantity()&&c.getBuyPrice()>0&&c.getSellPrice()>c.getBuyPrice()&&c.getTotalCost()==(long)c.getBuyPrice()*s.getExactRemainderQuantity()&&c.getRawSpreadPerItem()==(long)c.getSellPrice()-c.getBuyPrice()&&c.getNetMarginPerItem()>0&&c.getTotalTax()==(long)c.getTaxPerItem()*c.getExactRemainderQuantity()&&c.getTotalNetMargin()==c.getNetMarginPerItem()*c.getExactRemainderQuantity();}
 private static boolean valid(FillEstimate e){return e!=null&&Double.isFinite(e.getProbability())&&e.getProbability()>=0&&e.getProbability()<=1&&!Double.isNaN(e.getExpectedHours())&&e.getExpectedHours()>=0&&Double.isFinite(e.getUnitsPerHour())&&e.getUnitsPerHour()>=0&&!Double.isNaN(e.getWaitHours())&&e.getWaitHours()>=0;}
}
