package com.flippingfriend.core;

/** Closed, machine-readable reasons why a policy deliberately produced no manual action. */
public enum PolicyAbstentionReason
{
    NONE,
    COMPANION_UNAVAILABLE,
    MARKET_DATA_UNAVAILABLE,
    MARKET_DATA_STALE,
    ACCOUNT_STATE_UNAVAILABLE,
    ACCOUNT_RESTRICTED,
    ACCOUNT_STATE_INCONSISTENT,
    OFFER_STATE_INCONSISTENT,
    POSITION_COST_UNKNOWN,
    NO_FREE_SLOT,
    SLOT_RESERVED_FOR_EXIT,
    INSUFFICIENT_CAPITAL,
    BUY_LIMIT_EXHAUSTED,
    NO_ELIGIBLE_CANDIDATE,
    RISK_CONSTRAINT,
    BLOCKED_ITEM,
    SKIPPED_ITEM,
    ITEM_ALREADY_ON_OFFER,
    MEMBERSHIP_RESTRICTION,
    SELL_ONLY_MODE,
    DRAWDOWN_LIMIT_REACHED,
    PRICE_HISTORY_UNAVAILABLE,
    FILL_ESTIMATE_UNAVAILABLE,
    RECONCILIATION_REQUIRED,
    TRADING_SUSPENDED
}
