package com.flippingfriend.companion;
import org.junit.Test; import static org.junit.Assert.*;
public class BuyReplacementExpectedProfitEvaluatorTest {
 @Test public void appliesProductionCompletedAndStrandedFormulaInOrder(){BuyReplacementUnwindLossEvaluationSet s=source();BuyReplacementExpectedProfitEvaluationSet r=new BuyReplacementExpectedProfitEvaluator().evaluate(s,1100);assertNotNull(r);assertEquals(s.getEvaluations().size(),r.getEvaluations().size());for(int i=0;i<r.getEvaluations().size();i++){BuyReplacementUnwindLossEvaluation a=s.getEvaluations().get(i);BuyReplacementExpectedProfitEvaluation e=r.getEvaluations().get(i);double completed=a.getBuyProbability()*a.getSellProbability();double stranded=a.getBuyProbability()*(1-a.getSellProbability());double expected=completed*a.getTotalNetMargin()-stranded*a.getTotalUnwindLoss();assertEquals(completed,e.getCompletedProbability(),0.0);assertEquals(stranded,e.getStrandedProbability(),0.0);assertEquals(expected,e.getExpectedProfit(),0.0);assertEquals(a.getSellOffsetIndex(),e.getSellOffsetIndex());}try{r.getEvaluations().clear();fail("immutable");}catch(UnsupportedOperationException expected){}}
 @Test public void unavailableAndStaleInputsFailClosed(){BuyReplacementExpectedProfitEvaluator e=new BuyReplacementExpectedProfitEvaluator();assertNull(e.evaluate(null,1100));assertNull(e.evaluate(source(),1221));}
 @Test public void contractsCarryNoWorstLossSizingThroughputRankingSelectionOrAuthorization()throws Exception{for(String f:new String[]{"BuyReplacementExpectedProfitEvaluation.java","BuyReplacementExpectedProfitEvaluationSet.java"}){String x=java.nio.file.Files.readString(java.nio.file.Path.of("src/main/java/com/flippingfriend/companion/"+f));for(String forbidden:new String[]{"worstLoss","kelly","expectedGpPerSlotHour","positionSize","selected","score","rank","PortfolioCandidate","PolicyDecision","OfferLifecycleAction","REPLACEMENT_AUTHORIZED"})assertFalse(x.contains(forbidden));}}
 static BuyReplacementExpectedProfitEvaluationSet worstLossSourceForCompanionTests(){return evaluationSetForCompanionTests();}
 static BuyReplacementExpectedProfitEvaluationSet evaluationSetForCompanionTests(){return new BuyReplacementExpectedProfitEvaluator().evaluate(source(),1100);} private static BuyReplacementUnwindLossEvaluationSet source(){return BuyReplacementUnwindLossEvaluatorTest.expectedProfitSourceForCompanionTests();}
}
