package com.flippingfriend.companion;
import com.flippingfriend.data.Candle; import com.flippingfriend.model.TaxCalculator; import java.util.ArrayList; import java.util.Arrays; import java.util.List; import org.junit.Test; import static org.junit.Assert.*;
public class BuyReplacementSellFillInputContextComposerTest {
 @Test public void eligibleEvidenceAndHistoryProduceImmutableInputs(){List<Candle> h=history();BuyReplacementSellFillInputContext r=composer().compose(eligible(),h,1100,1100);assertNotNull(r);assertEquals(2,r.getCandidates().size());assertFalse(r.getFillCurve().isEmpty());assertSame(r.getFillCurve(),r.getFillCurve());h.get(0).setTimestamp(5000);assertEquals(300,r.getFillCurve().getWindowSeconds());try{r.getCandidates().clear();fail("immutable");}catch(UnsupportedOperationException expected){}}
 @Test public void unavailableStaleAndMalformedInputsFailClosed(){BuyReplacementNetMarginEligibilityAssessment e=eligible();assertNull(composer().compose(null,history(),1100,1100));assertNull(composer().compose(e,null,1100,1100));assertNull(composer().compose(e,new ArrayList<>(),1100,1100));assertNull(composer().compose(e,history(),1100,1221));List<Candle> future=history();future.get(1).setTimestamp(1101);assertNull(composer().compose(e,future,1100,1100));}
 @Test public void contractCarriesNoEstimateRankingSelectionOrAuthorization()throws Exception{String s=java.nio.file.Files.readString(java.nio.file.Path.of("src/main/java/com/flippingfriend/companion/BuyReplacementSellFillInputContext.java"));for(String x:new String[]{"FillEstimate","FillModel","selected","score","rank","PolicyDecision","OfferLifecycleAction","REPLACEMENT_AUTHORIZED"})assertFalse(s.contains(x));}
 static BuyReplacementSellFillInputContext contextForCompanionTests(){return composer().compose(eligible(),history(),1100,1100);}
 private static BuyReplacementSellFillInputContextComposer composer(){return new BuyReplacementSellFillInputContextComposer();} private static List<Candle> history(){return new ArrayList<>(Arrays.asList(new Candle(400,1000,990,20,20),new Candle(700,1001,991,20,20)));} private static BuyReplacementNetMarginEligibilityAssessment eligible(){TaxCalculator tax=new TaxCalculator(){@Override public int taxPerItem(int item,int sell){return sell>=509?0:10;}};BuyReplacementNetMarginEvaluationSet set=BuyReplacementNetMarginEvaluatorTest.setForCompanionTests(tax);return new BuyReplacementNetMarginEligibilityEvaluator().evaluate(set,tax,1002);}
}
