package com.flippingfriend.companion;
import com.flippingfriend.model.TaxCalculator; import org.junit.Test; import static org.junit.Assert.*;
public class BuyReplacementNetMarginEligibilityEvaluatorTest {
 @Test public void mixedEvidencePreservesCompleteAndDerivesPositiveView(){TaxCalculator tax=mixedTax();BuyReplacementNetMarginEvaluationSet s=BuyReplacementNetMarginEvaluatorTest.setForCompanionTests(tax);BuyReplacementNetMarginEligibilityAssessment r=evaluator().evaluate(s,tax,1002);assertNotNull(r);assertEquals(BuyReplacementNetMarginEligibilityOutcome.ELIGIBLE,r.getOutcome());assertEquals(4,r.getEvaluations().size());assertEquals(2,r.getPositiveNetMarginCandidates().size());assertEquals(0,r.getPositiveNetMarginCandidates().get(0).getSellOffsetIndex());assertEquals(1,r.getPositiveNetMarginCandidates().get(1).getSellOffsetIndex());try{r.getPositiveNetMarginCandidates().clear();fail("immutable");}catch(UnsupportedOperationException expected){}}
 @Test public void allNonpositiveEvidenceIsIneligible(){TaxCalculator tax=new TaxCalculator();BuyReplacementNetMarginEligibilityAssessment r=evaluator().evaluate(BuyReplacementNetMarginEvaluatorTest.setForCompanionTests(tax),tax,1002);assertNotNull(r);assertEquals(BuyReplacementNetMarginEligibilityOutcome.INELIGIBLE,r.getOutcome());assertEquals(4,r.getEvaluations().size());assertTrue(r.getPositiveNetMarginCandidates().isEmpty());}
 @Test public void unavailableMismatchedAndStaleEvidenceFailClosed(){TaxCalculator tax=new TaxCalculator();BuyReplacementNetMarginEvaluationSet s=BuyReplacementNetMarginEvaluatorTest.setForCompanionTests(tax);assertNull(evaluator().evaluate(null,tax,1002));assertNull(evaluator().evaluate(s,null,1002));assertNull(evaluator().evaluate(s,tax,1000));assertNull(evaluator().evaluate(s,mixedTax(),1002));}
 @Test public void contractsCarryNoRankingSelectionOrAuthorization()throws Exception{String s=java.nio.file.Files.readString(java.nio.file.Path.of("src/main/java/com/flippingfriend/companion/BuyReplacementNetMarginEligibilityAssessment.java"));for(String x:new String[]{"preferred","winner","score","rank","PolicyDecision","OfferLifecycleAction","REPLACEMENT_AUTHORIZED"})assertFalse(s.contains(x));}
 private static BuyReplacementNetMarginEligibilityEvaluator evaluator(){return new BuyReplacementNetMarginEligibilityEvaluator();} private static TaxCalculator mixedTax(){return new TaxCalculator(){@Override public int taxPerItem(int item,int sell){return sell>=509?0:10;}};}
}
