package com.flippingfriend.companion;
import com.flippingfriend.model.FillModel; import org.junit.Test; import static org.junit.Assert.*;
public class BuyReplacementSellFillEvaluatorTest {
 @Test public void evaluatesEveryCandidateInOrder(){BuyReplacementSellFillEvaluationSet r=evaluator().evaluate(context(),1100);assertNotNull(r);assertEquals(2,r.getEvaluations().size());for(int i=0;i<2;i++){assertEquals(r.getCandidates().get(i).getSellOffsetIndex(),r.getEvaluations().get(i).getSellOffsetIndex());assertEquals(5,r.getEvaluations().get(i).getExactRemainderQuantity());}try{r.getEvaluations().clear();fail("immutable");}catch(UnsupportedOperationException expected){}}
 @Test public void measuredEvidenceIsPreserved(){BuyReplacementSellFillInputContext c=context();BuyReplacementSellFillEvaluationSet r=evaluator().evaluate(c,1100);assertNotNull(r);com.flippingfriend.model.FillEstimate e=new FillModel().estimateSell(c.getFillCurve(),c.getCandidates().get(0).getSellPrice(),c.getExactRemainderQuantity(),c.getEffectiveHorizonHours());assertEquals(e.getProbability(),r.getEvaluations().get(0).getSellProbability(),0.0);assertEquals(e.getExpectedHours(),r.getEvaluations().get(0).getSellExpectedHours(),0.0);assertEquals(e.getUnitsPerHour(),r.getEvaluations().get(0).getSellUnitsPerHour(),0.0);assertEquals(e.getWaitHours(),r.getEvaluations().get(0).getSellWaitHours(),0.0);}
 @Test public void unavailableAndStaleInputsFailClosed(){assertNull(evaluator().evaluate(null,1100));assertNull(new BuyReplacementSellFillEvaluator(null).evaluate(context(),1100));assertNull(evaluator().evaluate(context(),1099));assertNull(evaluator().evaluate(context(),1221));}
 @Test public void contractsCarryNoViabilityRankingSelectionOrAuthorization()throws Exception{for(String f:new String[]{"BuyReplacementSellFillEvaluation.java","BuyReplacementSellFillEvaluationSet.java"}){String s=java.nio.file.Files.readString(java.nio.file.Path.of("src/main/java/com/flippingfriend/companion/"+f));for(String x:new String[]{"isPlausible","combined","selected","preferred","winner","score","rank","PolicyDecision","OfferLifecycleAction","REPLACEMENT_AUTHORIZED"})assertFalse(s.contains(x));}}
 static BuyReplacementSellFillEvaluationSet evaluationSetForCompanionTests(){return evaluator().evaluate(context(),1100);}
 private static BuyReplacementSellFillEvaluator evaluator(){return new BuyReplacementSellFillEvaluator(new FillModel());} private static BuyReplacementSellFillInputContext context(){return BuyReplacementSellFillInputContextComposerTest.contextForCompanionTests();}
}
