package com.flippingfriend.companion;
import java.util.ArrayList; import java.util.List; import org.junit.Test; import static org.junit.Assert.*;
public class BuyReplacementQuantityFillViabilityEvaluatorTest {
 @Test public void bothLegsMustBePlausibleAndOrderIsPreserved(){BuyReplacementQuantityFillViabilityAssessment r=new BuyReplacementQuantityFillViabilityEvaluator().evaluate(source(false),1100);assertNotNull(r);assertEquals(BuyReplacementQuantityFillViabilityOutcome.VIABLE,r.getOutcome());assertEquals(r.getEvaluations().size(),r.getEvaluations().size());assertEquals(r.getEvaluations().size(),r.getViableCandidates().size());for(int i=0;i<r.getViableCandidates().size();i++){assertEquals(r.getEvaluations().get(i).getQuantity(),r.getViableCandidates().get(i).getQuantity());assertEquals(r.getEvaluations().get(i).getSizeGridIndex(),r.getViableCandidates().get(i).getSizeGridIndex());}try{r.getEvaluations().clear();fail("complete immutable");}catch(UnsupportedOperationException expected){}try{r.getViableCandidates().clear();fail("viable immutable");}catch(UnsupportedOperationException expected){}}
 @Test public void validAllNeverFillEvidenceIsNotViable(){BuyReplacementQuantityFillViabilityAssessment r=new BuyReplacementQuantityFillViabilityEvaluator().evaluate(source(true),1100);assertNotNull(r);assertEquals(BuyReplacementQuantityFillViabilityOutcome.NOT_VIABLE,r.getOutcome());assertEquals(source(true).getEvaluations().size(),r.getEvaluations().size());assertTrue(r.getViableCandidates().isEmpty());}
 @Test public void unavailableStaleAndMalformedEvidenceFailClosed(){BuyReplacementQuantityFillViabilityEvaluator v=new BuyReplacementQuantityFillViabilityEvaluator();assertNull(v.evaluate(null,1100));assertNull(v.evaluate(source(false),1221));BuyReplacementQuantityFillEvaluationSet b=base();List<BuyReplacementQuantityFillEvaluation> bad=new ArrayList<>(b.getEvaluations());BuyReplacementQuantityFillInput x=b.getInputs().get(0);bad.set(0,new BuyReplacementQuantityFillEvaluation(x,Double.NaN,1,1,1,0.5,1,1,1));assertNull(v.evaluate(new BuyReplacementQuantityFillEvaluationSet(context(),bad,1100),1100));}
 @Test public void contractsCarryNoModelEconomicsSelectionOrAuthorization()throws Exception{for(String f:new String[]{"BuyReplacementQuantityFillViableCandidate.java","BuyReplacementQuantityFillViabilityAssessment.java"}){String x=java.nio.file.Files.readString(java.nio.file.Path.of("src/main/java/com/flippingfriend/companion/"+f));for(String forbidden:new String[]{"FillModel","FillCurve","combined","correctedHours","expectedGpPerSlotHour","PortfolioCandidate","selected","preferred","winner","rank","PolicyDecision","OfferLifecycleAction","REPLACEMENT_AUTHORIZED"})assertFalse(x.contains(forbidden));}}
 static BuyReplacementQuantityFillViabilityAssessment quantityFillViabilityAssessmentForCompanionTests(){return viableAssessmentForCompanionTests();}
 static BuyReplacementQuantityFillViabilityAssessment viableAssessmentForCompanionTests(){return new BuyReplacementQuantityFillViabilityEvaluator().evaluate(source(false),1100);} private static BuyReplacementQuantityFillEvaluationSet source(boolean allNever){BuyReplacementQuantityFillEvaluationSet b=base();List<BuyReplacementQuantityFillEvaluation> out=new ArrayList<>();for(BuyReplacementQuantityFillEvaluation e:b.getEvaluations()){BuyReplacementQuantityFillInput x=input(b,e);out.add(allNever?new BuyReplacementQuantityFillEvaluation(x,0,Double.POSITIVE_INFINITY,0,Double.POSITIVE_INFINITY,0,Double.POSITIVE_INFINITY,0,Double.POSITIVE_INFINITY):new BuyReplacementQuantityFillEvaluation(x,0.6,1.2,100,0.2,0.5,1.4,90,0.3));}return new BuyReplacementQuantityFillEvaluationSet(context(),out,1100);} private static BuyReplacementQuantityFillInput input(BuyReplacementQuantityFillEvaluationSet b,BuyReplacementQuantityFillEvaluation e){for(BuyReplacementQuantityFillInput x:b.getInputs())if(x.getQuantity()==e.getQuantity()&&x.getSizeGridIndex()==e.getSizeGridIndex())return x;throw new AssertionError();} private static BuyReplacementQuantityFillEvaluationSet base(){return BuyReplacementQuantityFillEvaluatorTest.quantityFillEvaluationSetForCompanionTests();} private static BuyReplacementQuantityFillInputContext context(){return BuyReplacementQuantityFillInputContextComposerTest.quantityFillContextForCompanionTests();}
}
