package com.flippingfriend.companion;
import com.flippingfriend.model.TaxCalculator; import java.lang.reflect.Method; import java.lang.reflect.Modifier; import java.util.ArrayList; import java.util.Collections; import java.util.List; import org.junit.Test; import static org.junit.Assert.*;
public class BuyReplacementQuantityWorstLossEvaluatorTest {
 private final TaxCalculator tax=new TaxCalculator(); private final BuyReplacementQuantityWorstLossEvaluator evaluator=new BuyReplacementQuantityWorstLossEvaluator(tax);
 @Test public void appliesProductionMultiplicationCastFloorAndGeneratedQuantity()throws Exception{BuyReplacementQuantityWorstLossInputContext s=source();BuyReplacementQuantityWorstLossEvaluationSet r=evaluator.evaluate(s,1100);assertNotNull(r);assertSame(s,r.getSource());assertSame(s.getEvaluations(),r.getExpectedProfitEvaluations());assertEquals(s.getComposedAt(),r.getInputComposedAt());assertEquals(1100,r.getEvaluatedAt());for(Method g:s.getClass().getDeclaredMethods()){if(g.getParameterCount()!=0||g.getName().equals("getSource")||g.getName().equals("getEvaluations")||g.getName().equals("getComposedAt"))continue;assertEquals(g.invoke(s),r.getClass().getDeclaredMethod(g.getName()).invoke(r));}boolean below=false;for(int i=0;i<r.getEvaluations().size();i++){BuyReplacementQuantityExpectedProfitEvaluation a=s.getEvaluations().get(i);BuyReplacementQuantityWorstLossEvaluation e=r.getEvaluations().get(i);assertSame(a,e.getSource());assertEquals(a.getWorstLoss(),e.getUpstreamWorstLoss());long expected=Math.max(1,(long)(a.getBuyPrice()*s.getLossCutPct()*a.getQuantity()));assertEquals(expected,e.getQuantityWorstLoss());assertEquals(s.getLossCutPct(),e.getLossCutPct(),0);if(a.getQuantity()<s.getExactRemainderQuantity()){below=true;assertNotEquals(Math.max(1,(long)(a.getBuyPrice()*s.getLossCutPct()*s.getExactRemainderQuantity())),e.getQuantityWorstLoss());}}assertTrue(below);}
 @Test public void productionTruncationAndOneCoinFloorArePinned(){assertEquals(1,evaluateRaw(1,0.02,1));assertEquals(1,evaluateRaw(99,0.02,1));assertEquals(2,evaluateRaw(101,0.02,1));assertEquals(10,evaluateRaw(101,0.05,2));}
 @Test public void inclusiveFreshnessUnavailableAndOverflowFailClosed(){assertNotNull(evaluator.evaluate(source(),1220));assertNull(evaluator.evaluate(source(),1221));assertNull(evaluator.evaluate(source(),1099));assertNull(evaluator.evaluate(source(),Long.MAX_VALUE));assertNull(evaluator.evaluate(null,1100));assertNull(new BuyReplacementQuantityWorstLossEvaluator(null).evaluate(source(),1100));}
 @Test public void reorderedNullEmptyForeignAndAlteredEvidenceFailClosed(){BuyReplacementQuantityWorstLossInputContext s=source();List<BuyReplacementQuantityExpectedProfitEvaluation> list=new ArrayList<>(s.getEvaluations());assertTrue(list.size()>1);Collections.reverse(list);assertBad(s,list);list=new ArrayList<>(s.getEvaluations());list.set(0,null);assertBad(s,list);list=new ArrayList<>(s.getEvaluations());list.set(0,source().getEvaluations().get(0));assertBad(s,list);BuyReplacementQuantityExpectedProfitEvaluation e=s.getEvaluations().get(0);list=new ArrayList<>(s.getEvaluations());list.set(0,new BuyReplacementQuantityExpectedProfitEvaluation(e.getSource(),e.getCompletedSaleNetProfit()+1,e.getCompletedProbability(),e.getStrandedProbability(),e.getQuantityExpectedProfit()));assertBad(s,list);assertBad(s,Collections.emptyList());}
 @Test public void alteredCanonicalLossCutFailsClosed(){BuyReplacementQuantityWorstLossInputContext s=source();assertNull(evaluator.evaluate(new BuyReplacementQuantityWorstLossInputContext(s.getSource(),s.getLossCutPct()+0.01,1100),1100));for(double x:new double[]{0,-1,Double.NaN,Double.POSITIVE_INFINITY})assertNull(evaluator.evaluate(new BuyReplacementQuantityWorstLossInputContext(s.getSource(),x,1100),1100));}
 @Test public void negativeExpectedProfitRemainsEvidence(){TaxCalculator negative=new TaxCalculator(){@Override public long netMarginPerItem(int i,int b,int s){return -5;}@Override public long netProfit(int i,int b,int s,int q){return -5L*q;}};BuyReplacementQuantityExpectedProfitEvaluationSet p=new BuyReplacementQuantityExpectedProfitEvaluator(negative).evaluate(BuyReplacementQuantityUnwindLossEvaluatorTest.evaluationSetForCompanionTests(),1100);BuyReplacementQuantityWorstLossInputContext c=new BuyReplacementQuantityWorstLossInputContextComposer(negative).compose(p,1100);BuyReplacementQuantityWorstLossEvaluationSet r=new BuyReplacementQuantityWorstLossEvaluator(negative).evaluate(c,1100);assertNotNull(r);assertTrue(r.getEvaluations().get(0).getQuantityExpectedProfit()<0);}
 @Test public void defensiveImmutableAndDeterministic(){BuyReplacementQuantityWorstLossInputContext s=source();BuyReplacementQuantityWorstLossEvaluationSet r=evaluator.evaluate(s,1100);List<BuyReplacementQuantityWorstLossEvaluation> copy=new ArrayList<>(r.getEvaluations());BuyReplacementQuantityWorstLossEvaluationSet d=new BuyReplacementQuantityWorstLossEvaluationSet(s,copy,1100);copy.clear();assertEquals(r.getEvaluations().size(),d.getEvaluations().size());try{r.getEvaluations().clear();fail("immutable");}catch(UnsupportedOperationException expected){}assertEquals(r.getEvaluations().get(0).getQuantityWorstLoss(),evaluator.evaluate(s,1100).getEvaluations().get(0).getQuantityWorstLoss());}
 @Test public void contractsRemainPackagePrivateAndOutsideLaterAuthority()throws Exception{for(Class<?> c:new Class<?>[]{BuyReplacementQuantityWorstLossEvaluation.class,BuyReplacementQuantityWorstLossEvaluationSet.class,BuyReplacementQuantityWorstLossEvaluator.class}){assertFalse(Modifier.isPublic(c.getModifiers()));String x=java.nio.file.Files.readString(java.nio.file.Path.of("src/main/java/com/flippingfriend/companion/"+c.getSimpleName()+".java"));for(String forbidden:new String[]{"kellyFraction(","expectedGpPerSlotHour","PortfolioCandidate","PortfolioOptimizer","PolicyDecision","OfferLifecycleAction","REPLACEMENT_AUTHORIZED","SqliteStore","schedule","selected","rank"})assertFalse(forbidden,x.contains(forbidden));}}
 static BuyReplacementQuantityWorstLossEvaluationSet evaluationSetForCompanionTests(){return new BuyReplacementQuantityWorstLossEvaluator(new TaxCalculator()).evaluate(source(),1100);}
 private static BuyReplacementQuantityWorstLossInputContext source(){return BuyReplacementQuantityWorstLossInputContextComposerTest.contextForCompanionTests();}
 private void assertBad(BuyReplacementQuantityWorstLossInputContext s,List<BuyReplacementQuantityExpectedProfitEvaluation> list){assertNull(evaluator.evaluate(new BuyReplacementQuantityWorstLossInputContext(new BuyReplacementQuantityExpectedProfitEvaluationSet(s.getSource().getSource(),list,1100),s.getLossCutPct(),1100),1100));}
 private static long evaluateRaw(int price,double loss,int quantity){double raw=price*loss*quantity;return Math.max(1,(long)raw);}
}
