package com.flippingfriend.companion;
import com.flippingfriend.model.TaxCalculator; import java.lang.reflect.Method; import java.lang.reflect.Modifier; import java.util.ArrayList; import java.util.Collections; import java.util.List; import org.junit.Test; import static org.junit.Assert.*;
public class BuyReplacementQuantityKellyFractionEvaluatorTest {
 private final TaxCalculator tax=new TaxCalculator(); private final BuyReplacementQuantityKellyFractionEvaluator evaluator=new BuyReplacementQuantityKellyFractionEvaluator(tax);
 @Test public void appliesExactProductionKellyArithmeticAndPreservesEveryGetter()throws Exception{BuyReplacementQuantityKellySizingInputContext s=source();BuyReplacementQuantityKellyFractionEvaluationSet r=evaluator.evaluate(s,1100);assertNotNull(r);assertSame(s,r.getSource());assertSame(s.getInputs(),r.getInputs());assertEquals(s.getComposedAt(),r.getInputComposedAt());assertEquals(1100,r.getEvaluatedAt());for(Method g:s.getClass().getDeclaredMethods()){if(g.getParameterCount()!=0||g.getName().equals("getSource")||g.getName().equals("getInputs")||g.getName().equals("getComposedAt"))continue;Object a=g.invoke(s),b=r.getClass().getDeclaredMethod(g.getName()).invoke(r);if(a instanceof double[])assertArrayEquals((double[])a,(double[])b,0);else assertEquals(a,b);}for(int i=0;i<r.getEvaluations().size();i++){BuyReplacementQuantityKellySizingInput a=s.getInputs().get(i);BuyReplacementQuantityKellyFractionEvaluation e=r.getEvaluations().get(i);assertSame(a,e.getSource());assertEquals(CandidateFactory.kellyFraction(a.getCompletionProbability(),a.getPayoffOdds()),e.getQuantityKellyFraction(),0);assertEquals(a.getQuantity(),e.getQuantity());assertEquals(a.getQuantityWorstLoss(),e.getQuantityWorstLoss());}}
 @Test public void floorCeilingShareAndEdgeOrderMatchProduction(){for(double p:new double[]{0,0.01,0.3,0.7,1})for(double b:new double[]{-2,0,0.1,1,10,Double.MAX_VALUE})assertEquals(CandidateFactory.kellyFraction(p,b),BuyReplacementQuantityKellyFractionEvaluator.kellyFraction(p,b,0.35,0.1),0);assertEquals(0.1,BuyReplacementQuantityKellyFractionEvaluator.kellyFraction(0.5,0,0.35,0.1),0);assertEquals(1,BuyReplacementQuantityKellyFractionEvaluator.kellyFraction(1,0.01,2,0.1),0);}
 @Test public void finiteNonpositivePayoffOddsMapToMinimumFraction(){TaxCalculator negative=new TaxCalculator(){@Override public long netMarginPerItem(int i,int b,int s){return -5;}@Override public long netProfit(int i,int b,int s,int q){return -5L*q;}};BuyReplacementQuantityExpectedProfitEvaluationSet p=new BuyReplacementQuantityExpectedProfitEvaluator(negative).evaluate(BuyReplacementQuantityUnwindLossEvaluatorTest.evaluationSetForCompanionTests(),1100);BuyReplacementQuantityWorstLossInputContext c=new BuyReplacementQuantityWorstLossInputContextComposer(negative).compose(p,1100);BuyReplacementQuantityWorstLossEvaluationSet w=new BuyReplacementQuantityWorstLossEvaluator(negative).evaluate(c,1100);BuyReplacementQuantityKellySizingInputContext x=new BuyReplacementQuantityKellySizingInputContextComposer(negative).compose(w,1100);BuyReplacementQuantityKellyFractionEvaluationSet r=new BuyReplacementQuantityKellyFractionEvaluator(negative).evaluate(x,1100);assertNotNull(r);for(BuyReplacementQuantityKellyFractionEvaluation e:r.getEvaluations())assertEquals(0.1,e.getQuantityKellyFraction(),0);}
 @Test public void inclusiveFreshnessUnavailableAndInvalidConstantsFailClosed(){assertNotNull(evaluator.evaluate(source(),1220));assertNull(evaluator.evaluate(source(),1221));assertNull(evaluator.evaluate(source(),1099));assertNull(evaluator.evaluate(source(),Long.MAX_VALUE));assertNull(evaluator.evaluate(null,1100));assertNull(new BuyReplacementQuantityKellyFractionEvaluator(null).evaluate(source(),1100));BuyReplacementQuantityKellySizingInputContext s=source();for(double bad:new double[]{0,-1,Double.NaN,Double.POSITIVE_INFINITY})assertNull(evaluator.evaluate(copy(s,s.getInputs(),bad,0.1,s.getSizeGrid()),1100));for(double bad:new double[]{0,-1,Double.NaN,Double.POSITIVE_INFINITY,1.1})assertNull(evaluator.evaluate(copy(s,s.getInputs(),0.35,bad,s.getSizeGrid()),1100));assertNull(evaluator.evaluate(copy(s,s.getInputs(),0.35,0.1,new double[]{0.5,2,1,4,8}),1100));}
 @Test public void reorderedNullEmptyForeignAndAlteredEvidenceFailClosed(){BuyReplacementQuantityKellySizingInputContext s=source();List<BuyReplacementQuantityKellySizingInput> list=new ArrayList<>(s.getInputs());assertTrue(list.size()>1);Collections.reverse(list);assertBad(s,list);list=new ArrayList<>(s.getInputs());list.set(0,null);assertBad(s,list);list=new ArrayList<>(s.getInputs());list.set(0,source().getInputs().get(0));assertBad(s,list);BuyReplacementQuantityKellySizingInput e=s.getInputs().get(0);list=new ArrayList<>(s.getInputs());list.set(0,new BuyReplacementQuantityKellySizingInput(e.getSource(),e.getQuantityNetProfit(),e.getQuantityUnwindLoss(),e.getQuantityWorstLoss()+1,e.getCompletionProbability(),e.getPayoffOdds()));assertBad(s,list);assertBad(s,Collections.emptyList());}
 @Test public void invalidProbabilityAndNonfiniteOddsFailClosed(){BuyReplacementQuantityKellySizingInputContext s=source();BuyReplacementQuantityKellySizingInput e=s.getInputs().get(0);for(double p:new double[]{-1,0,1.1,Double.NaN,Double.POSITIVE_INFINITY})assertBadFirst(s,new BuyReplacementQuantityKellySizingInput(e.getSource(),e.getQuantityNetProfit(),e.getQuantityUnwindLoss(),e.getQuantityWorstLoss(),p,e.getPayoffOdds()));for(double b:new double[]{Double.NaN,Double.POSITIVE_INFINITY,Double.NEGATIVE_INFINITY})assertBadFirst(s,new BuyReplacementQuantityKellySizingInput(e.getSource(),e.getQuantityNetProfit(),e.getQuantityUnwindLoss(),e.getQuantityWorstLoss(),e.getCompletionProbability(),b));}
 @Test public void defensiveImmutableAndDeterministic(){BuyReplacementQuantityKellySizingInputContext s=source();BuyReplacementQuantityKellyFractionEvaluationSet r=evaluator.evaluate(s,1100);List<BuyReplacementQuantityKellyFractionEvaluation> copy=new ArrayList<>(r.getEvaluations());BuyReplacementQuantityKellyFractionEvaluationSet d=new BuyReplacementQuantityKellyFractionEvaluationSet(s,copy,1100);copy.clear();assertEquals(r.getEvaluations().size(),d.getEvaluations().size());try{r.getEvaluations().clear();fail("immutable");}catch(UnsupportedOperationException expected){}assertEquals(r.getEvaluations().get(0).getQuantityKellyFraction(),evaluator.evaluate(s,1100).getEvaluations().get(0).getQuantityKellyFraction(),0);}
 @Test public void contractsRemainPackagePrivateWithoutQuantityGridOrAuthority()throws Exception{for(Class<?> c:new Class<?>[]{BuyReplacementQuantityKellyFractionEvaluation.class,BuyReplacementQuantityKellyFractionEvaluationSet.class,BuyReplacementQuantityKellyFractionEvaluator.class}){assertFalse(Modifier.isPublic(c.getModifiers()));String x=java.nio.file.Files.readString(java.nio.file.Path.of("src/main/java/com/flippingfriend/companion/"+c.getSimpleName()+".java"));for(String forbidden:new String[]{"Math.round","expectedGpPerSlotHour","PortfolioCandidate","PortfolioOptimizer","PolicyDecision","OfferLifecycleAction","REPLACEMENT_AUTHORIZED","SqliteStore","schedule","selected","rank"})assertFalse(forbidden,x.contains(forbidden));}}
 static BuyReplacementQuantityKellyFractionEvaluationSet evaluationSetForCompanionTests(){return new BuyReplacementQuantityKellyFractionEvaluator(new TaxCalculator()).evaluate(source(),1100);}
 private static BuyReplacementQuantityKellySizingInputContext source(){return BuyReplacementQuantityKellySizingInputContextComposerTest.contextForCompanionTests();}
 private static BuyReplacementQuantityKellySizingInputContext copy(BuyReplacementQuantityKellySizingInputContext s,List<BuyReplacementQuantityKellySizingInput> inputs,double share,double minimum,double[] grid){return new BuyReplacementQuantityKellySizingInputContext(s.getSource(),inputs,share,minimum,grid,1100);}
 private void assertBad(BuyReplacementQuantityKellySizingInputContext s,List<BuyReplacementQuantityKellySizingInput> inputs){assertNull(evaluator.evaluate(copy(s,inputs,s.getKellyShare(),s.getMinimumKellyFraction(),s.getSizeGrid()),1100));}
 private void assertBadFirst(BuyReplacementQuantityKellySizingInputContext s,BuyReplacementQuantityKellySizingInput bad){List<BuyReplacementQuantityKellySizingInput> list=new ArrayList<>(s.getInputs());list.set(0,bad);assertBad(s,list);}
}
