package com.flippingfriend.companion;
import com.flippingfriend.model.FillEstimate; import com.flippingfriend.model.FillModel; import org.junit.Test; import static org.junit.Assert.*;
public class BuyReplacementQuantityFillEvaluatorTest {
 @Test public void evaluatesBothLegsForEveryGeneratedQuantityInOrder(){BuyReplacementQuantityFillInputContext c=context();BuyReplacementQuantityFillEvaluationSet r=evaluator().evaluate(c,1100);assertNotNull(r);assertEquals(c.getInputs().size(),r.getEvaluations().size());for(int i=0;i<r.getEvaluations().size();i++){BuyReplacementQuantityFillInput x=c.getInputs().get(i);BuyReplacementQuantityFillEvaluation v=r.getEvaluations().get(i);assertEquals(x.getQuantity(),v.getQuantity());assertEquals(x.getSizeGridIndex(),v.getSizeGridIndex());assertEquals(x.getSizeShare(),v.getSizeShare(),0.0);}try{r.getEvaluations().clear();fail("immutable");}catch(UnsupportedOperationException expected){}}
 @Test public void measurementsMatchProductionSeasonalOverloads(){BuyReplacementQuantityFillInputContext c=context();BuyReplacementQuantityFillEvaluationSet r=evaluator().evaluate(c,1100);BuyReplacementQuantityFillInput x=c.getInputs().get(0);FillModel m=new FillModel();FillEstimate b=m.estimateBuy(c.getFillCurve(),x.getBuyPrice(),x.getQuantity(),c.getEffectiveHorizonHours(),c.getSeasonalMultiplier());FillEstimate s=m.estimateSell(c.getFillCurve(),x.getSellPrice(),x.getQuantity(),c.getEffectiveHorizonHours(),c.getSeasonalMultiplier());assertEquals(b.getProbability(),r.getEvaluations().get(0).getBuyProbability(),0.0);assertEquals(b.getExpectedHours(),r.getEvaluations().get(0).getBuyExpectedHours(),0.0);assertEquals(b.getUnitsPerHour(),r.getEvaluations().get(0).getBuyUnitsPerHour(),0.0);assertEquals(b.getWaitHours(),r.getEvaluations().get(0).getBuyWaitHours(),0.0);assertEquals(s.getProbability(),r.getEvaluations().get(0).getSellProbability(),0.0);assertEquals(s.getExpectedHours(),r.getEvaluations().get(0).getSellExpectedHours(),0.0);assertEquals(s.getUnitsPerHour(),r.getEvaluations().get(0).getSellUnitsPerHour(),0.0);assertEquals(s.getWaitHours(),r.getEvaluations().get(0).getSellWaitHours(),0.0);}
 @Test public void unavailableAndStaleInputsFailClosed(){assertNull(evaluator().evaluate(null,1100));assertNull(new BuyReplacementQuantityFillEvaluator(null).evaluate(context(),1100));assertNull(evaluator().evaluate(context(),1099));assertNull(evaluator().evaluate(context(),1221));}
 @Test public void contractsCarryNoPlausibilityEconomicsSelectionOrAuthorization()throws Exception{for(String f:new String[]{"BuyReplacementQuantityFillEvaluation.java","BuyReplacementQuantityFillEvaluationSet.java"}){String x=java.nio.file.Files.readString(java.nio.file.Path.of("src/main/java/com/flippingfriend/companion/"+f));for(String forbidden:new String[]{"isPlausible","correctedHours","expectedGpPerSlotHour","PortfolioCandidate","selected","preferred","winner","rank","PolicyDecision","OfferLifecycleAction","REPLACEMENT_AUTHORIZED"})assertFalse(x.contains(forbidden));}}
 static BuyReplacementQuantityFillEvaluationSet evaluationSetForCompanionTests(){return evaluator().evaluate(context(),1100);} private static BuyReplacementQuantityFillEvaluator evaluator(){return new BuyReplacementQuantityFillEvaluator(new FillModel());} private static BuyReplacementQuantityFillInputContext context(){return BuyReplacementQuantityFillInputContextComposerTest.quantityFillContextForCompanionTests();}
}
