package com.flippingfriend.companion;
import com.flippingfriend.model.TaxCalculator; import java.lang.reflect.Method; import java.lang.reflect.Modifier; import java.util.ArrayList; import java.util.Collections; import java.util.List; import org.junit.Test; import static org.junit.Assert.*;
public class BuyReplacementQuantityKellySizingInputContextComposerTest {
 private final TaxCalculator tax=new TaxCalculator(); private final BuyReplacementQuantityKellySizingInputContextComposer composer=new BuyReplacementQuantityKellySizingInputContextComposer(tax);
 @Test public void bindsGeneratedQuantityProductionKellyInputsConstantsAndEveryGetter()throws Exception{BuyReplacementQuantityWorstLossEvaluationSet s=source();BuyReplacementQuantityKellySizingInputContext r=composer.compose(s,1100);assertNotNull(r);assertSame(s,r.getSource());assertSame(s.getEvaluations(),r.getWorstLossEvaluations());assertEquals(0.35,r.getKellyShare(),0);assertEquals(0.1,r.getMinimumKellyFraction(),0);assertArrayEquals(new double[]{0.5,1,2,4,8},r.getSizeGrid(),0);assertEquals(s.getEvaluatedAt(),r.getWorstLossEvaluatedAt());assertEquals(1100,r.getComposedAt());for(Method g:s.getClass().getDeclaredMethods()){if(g.getParameterCount()!=0||g.getName().equals("getSource")||g.getName().equals("getEvaluations")||g.getName().equals("getEvaluatedAt"))continue;assertEquals(g.invoke(s),r.getClass().getDeclaredMethod(g.getName()).invoke(r));}assertEquals(s.getEvaluations().size(),r.getInputs().size());for(int i=0;i<r.getInputs().size();i++){BuyReplacementQuantityWorstLossEvaluation e=s.getEvaluations().get(i);BuyReplacementQuantityKellySizingInput x=r.getInputs().get(i);assertSame(e,x.getSource());assertEquals(e.getQuantity(),x.getQuantity());assertEquals(e.getCompletedSaleNetProfit(),x.getQuantityNetProfit());assertEquals(e.getTotalUnwindLoss(),x.getQuantityUnwindLoss());assertEquals(e.getQuantityWorstLoss(),x.getQuantityWorstLoss());assertEquals(e.getCompletionProbability(),x.getCompletionProbability(),0);double odds=e.getTotalUnwindLoss()>0?(double)e.getCompletedSaleNetProfit()/e.getTotalUnwindLoss():e.getCompletedSaleNetProfit();assertEquals(odds,x.getPayoffOdds(),0);}}
 @Test public void sizeGridAndInputListAreDefensiveImmutableAndOrdered(){BuyReplacementQuantityKellySizingInputContext r=composer.compose(source(),1100);double[] grid=r.getSizeGrid();grid[0]=99;assertEquals(0.5,r.getSizeGrid()[0],0);try{r.getInputs().clear();fail("immutable");}catch(UnsupportedOperationException expected){}for(int i=0;i<r.getInputs().size();i++)assertSame(r.getWorstLossEvaluations().get(i),r.getInputs().get(i).getSource());}
 @Test public void payoffOddsPreserveProductionSemanticsIncludingNonpositiveEvidence(){BuyReplacementQuantityWorstLossEvaluationSet s=source();BuyReplacementQuantityWorstLossEvaluation e=s.getEvaluations().get(0);assertEquals(e.getTotalUnwindLoss()>0?(double)e.getCompletedSaleNetProfit()/e.getTotalUnwindLoss():e.getCompletedSaleNetProfit(),composer.compose(s,1100).getInputs().get(0).getPayoffOdds(),0);}
 @Test public void inclusiveFreshnessUnavailableAndFutureTimeFailClosed(){assertNotNull(composer.compose(source(),1220));assertNull(composer.compose(source(),1221));assertNull(composer.compose(source(),1099));assertNull(composer.compose(source(),Long.MAX_VALUE));assertNull(composer.compose(null,1100));assertNull(new BuyReplacementQuantityKellySizingInputContextComposer(null).compose(source(),1100));}
 @Test public void reorderedNullEmptyForeignAndAlteredEvidenceFailClosed(){BuyReplacementQuantityWorstLossEvaluationSet s=source();List<BuyReplacementQuantityWorstLossEvaluation> list=new ArrayList<>(s.getEvaluations());assertTrue(list.size()>1);Collections.reverse(list);assertBad(s,list);list=new ArrayList<>(s.getEvaluations());list.set(0,null);assertBad(s,list);list=new ArrayList<>(s.getEvaluations());list.set(0,source().getEvaluations().get(0));assertBad(s,list);BuyReplacementQuantityWorstLossEvaluation e=s.getEvaluations().get(0);list=new ArrayList<>(s.getEvaluations());list.set(0,new BuyReplacementQuantityWorstLossEvaluation(e.getSource(),e.getLossCutPct(),e.getQuantityWorstLoss()+1));assertBad(s,list);assertBad(s,Collections.emptyList());}
 @Test public void nonpositiveCompletedPayoffRemainsEvidenceForProductionFloorHandling(){TaxCalculator negative=new TaxCalculator(){@Override public long netMarginPerItem(int i,int b,int s){return -5;}@Override public long netProfit(int i,int b,int s,int q){return -5L*q;}};BuyReplacementQuantityExpectedProfitEvaluationSet p=new BuyReplacementQuantityExpectedProfitEvaluator(negative).evaluate(BuyReplacementQuantityUnwindLossEvaluatorTest.evaluationSetForCompanionTests(),1100);BuyReplacementQuantityWorstLossInputContext c=new BuyReplacementQuantityWorstLossInputContextComposer(negative).compose(p,1100);BuyReplacementQuantityWorstLossEvaluationSet w=new BuyReplacementQuantityWorstLossEvaluator(negative).evaluate(c,1100);assertNotNull(w);BuyReplacementQuantityKellySizingInputContext r=new BuyReplacementQuantityKellySizingInputContextComposer(negative).compose(w,1100);assertNotNull(r);assertTrue(r.getInputs().get(0).getPayoffOdds()<=0);}
 @Test public void deterministicCompositionDoesNotRefreshWorstLossTimestamp(){BuyReplacementQuantityWorstLossEvaluationSet s=source();BuyReplacementQuantityKellySizingInputContext a=composer.compose(s,1150),b=composer.compose(s,1150);assertNotNull(a);assertNotNull(b);assertSame(a.getSource(),b.getSource());assertEquals(a.getInputs().size(),b.getInputs().size());assertEquals(1100,a.getWorstLossEvaluatedAt());assertEquals(1150,a.getComposedAt());}
 @Test public void contractsRemainPackagePrivateAndCarryNoFractionQuantityOrAuthority()throws Exception{for(Class<?> c:new Class<?>[]{BuyReplacementQuantityKellySizingInput.class,BuyReplacementQuantityKellySizingInputContext.class,BuyReplacementQuantityKellySizingInputContextComposer.class}){assertFalse(Modifier.isPublic(c.getModifiers()));String x=java.nio.file.Files.readString(java.nio.file.Path.of("src/main/java/com/flippingfriend/companion/"+c.getSimpleName()+".java"));for(String forbidden:new String[]{"kellyFraction(","Math.round","expectedGpPerSlotHour","PortfolioCandidate","PortfolioOptimizer","PolicyDecision","OfferLifecycleAction","REPLACEMENT_AUTHORIZED","SqliteStore","schedule","selected","rank"})assertFalse(forbidden,x.contains(forbidden));}}
 static BuyReplacementQuantityKellySizingInputContext contextForCompanionTests(){return new BuyReplacementQuantityKellySizingInputContextComposer(new TaxCalculator()).compose(source(),1100);}
 private static BuyReplacementQuantityWorstLossEvaluationSet source(){return BuyReplacementQuantityWorstLossEvaluatorTest.evaluationSetForCompanionTests();}
 private void assertBad(BuyReplacementQuantityWorstLossEvaluationSet s,List<BuyReplacementQuantityWorstLossEvaluation> list){assertNull(composer.compose(new BuyReplacementQuantityWorstLossEvaluationSet(s.getSource(),list,1100),1100));}
}
