package com.flippingfriend.companion;
import com.flippingfriend.core.AccountSnapshot; import java.util.Collections; import org.junit.Test; import static org.junit.Assert.*;
public class BuyReplacementPricingStrategyContextComposerTest {
 private final BuyReplacementPricingStrategyContextComposer composer=new BuyReplacementPricingStrategyContextComposer();
 @Test public void exactAuthorityBindsLineageStrategyAndHorizon(){BuyReplacementPricingStrategyContext r=composer.compose(context(),account("LOW",30,0));assertNotNull(r);assertEquals("intent-1",r.getIntentId());assertEquals("offer-1",r.getOriginalOfferIdentity());assertEquals("plan-1",r.getRecommendationId());assertEquals(400,r.getExactRemainderQuantity());assertEquals("Cautious",r.getAppetiteName());assertArrayEquals(new double[]{0,.0015,.004},r.getBuyOffsets(),0);assertEquals(1.5,r.getEffectiveHorizonHours(),0);}
 @Test public void productionMappingAndHorizonArePreserved(){assertEquals("Aggressive",composer.compose(context(),account("HIGH",0,0)).getAppetiteName());assertEquals("Balanced",composer.compose(context(),account(null,0,0)).getAppetiteName());assertEquals("Balanced",composer.compose(context(),account("unknown",0,0)).getAppetiteName());assertEquals(2.0,composer.compose(context(),account("LOW",150,60)).getEffectiveHorizonHours(),0);}
 @Test public void offsetsAreDefensive(){BuyReplacementPricingStrategyContext r=composer.compose(context(),account("HIGH",0,0));double[] x=r.getBuyOffsets();x[0]=9;assertEquals(0,r.getBuyOffsets()[0],0);}
 @Test public void mismatchedAccountFailsClosed(){assertNull(composer.compose(context(),null));assertNull(composer.compose(context(),accountAt("LOW",899,2000000,true,true,1,8)));assertNull(composer.compose(context(),accountAt("LOW",900,1999999,true,true,1,8)));assertNull(composer.compose(context(),accountAt("LOW",900,2000000,false,true,1,8)));assertNull(composer.compose(context(),accountAt("LOW",900,2000000,true,false,1,8)));assertNull(composer.compose(context(),accountAt("LOW",900,2000000,true,true,0,8)));}
 @Test public void malformedPricingFailsClosed(){assertNull(composer.compose(context(400,399,990,1010,900,900,1000,1100),account("LOW",0,0)));assertNull(composer.compose(context(400,400,1010,1010,900,900,1000,1100),account("LOW",0,0)));assertNull(composer.compose(context(400,400,990,1010,879,900,1000,1100),accountAt("LOW",879,2000000,true,true,1,8)));assertNull(composer.compose(context(400,400,990,1010,900,900,1001,1000),account("LOW",0,0)));}
 @Test public void carriesNoProposalActionOrAuthorization()throws Exception{String s=java.nio.file.Files.readString(java.nio.file.Path.of("src/main/java/com/flippingfriend/companion/BuyReplacementPricingStrategyContext.java"));assertFalse(s.contains("PriceOffset"));assertFalse(s.contains("proposedPrice"));assertFalse(s.contains("OfferLifecycleAction"));assertFalse(s.contains("PolicyDecision"));assertFalse(s.contains("REPLACEMENT_AUTHORIZED"));}
 private static BuyReplacementPricingContext context(){return context(400,400,990,1010,900,900,1000,1100);} private static BuyReplacementPricingContext context(int q,int l,int low,int high,long aa,long ma,long at,long ex){return new BuyReplacementPricingContext("assessment-1","readiness-1","intent-1","offer-1","plan-1",2,4151,"Abyssal whip",q,1000,low,high,l,2000000,true,100,ex,aa,ma,Math.min(aa,ma),at);}
 private static AccountSnapshot account(String r,int check,int target){return accountAt(r,900,2000000,true,true,1,8,check,target);} private static AccountSnapshot accountAt(String r,long at,long c,boolean m,boolean b,int f,int t){return accountAt(r,at,c,m,b,f,t,0,0);} private static AccountSnapshot accountAt(String r,long at,long c,boolean m,boolean b,int f,int t,int check,int target){return new AccountSnapshot("a",at,c,0,f,t,m,b,0,r,Collections.emptyMap(),0,Collections.emptyMap(),false,check,Collections.emptySet(),Collections.emptySet(),Collections.emptySet(),false,target);}
}
