package com.flippingfriend.companion;
import org.junit.Test; import static org.junit.Assert.*;
public class BuyReplacementSpreadEligibilityEvaluatorTest {
 @Test public void mixedGridPreservesCompleteAndDerivesPositiveView(){BuyReplacementSpreadEligibilityAssessment r=evaluator().evaluate(set(),1000);assertNotNull(r);assertEquals(BuyReplacementSpreadEligibilityOutcome.ELIGIBLE,r.getOutcome());assertEquals(4,r.getCandidates().size());assertEquals(4,r.getPositiveSpreadCandidates().size());assertEquals(9,r.getPositiveSpreadCandidates().get(0).getRawSpreadPerItem());try{r.getPositiveSpreadCandidates().clear();fail("immutable");}catch(UnsupportedOperationException expected){}}
 @Test public void validAllNonpositiveGridIsIneligible(){BuyReplacementSellPricingStrategyContext s=BuyReplacementSellPricingStrategyContextComposerTest.strategyForHighForCompanionTests(500);BuyReplacementSellPriceCandidateSet raw=new BuyReplacementSellPriceCandidateComposer().compose(s);BuyReplacementSpreadEligibilityAssessment r=evaluator().evaluate(raw,1000);assertNotNull(r);assertEquals(BuyReplacementSpreadEligibilityOutcome.INELIGIBLE,r.getOutcome());assertEquals(4,r.getCandidates().size());assertTrue(r.getPositiveSpreadCandidates().isEmpty());}
 @Test public void missingAndIncompleteEvidenceFailsClosed(){assertNull(evaluator().evaluate(null,1000));BuyReplacementSellPriceCandidateSet s=set();assertNull(evaluator().evaluate(new BuyReplacementSellPriceCandidateSet(BuyReplacementSellPricingStrategyContextComposerTest.strategyForCompanionTests(),s.getCandidates().subList(0,3)),1000));}
 @Test public void contractsCarryNoTaxProfitSelectionOrAuthorization()throws Exception{String s=java.nio.file.Files.readString(java.nio.file.Path.of("src/main/java/com/flippingfriend/companion/BuyReplacementSpreadEligibilityAssessment.java"));for(String x:new String[]{"TaxCalculator","netMargin","profit","selected","preferred","PolicyDecision","OfferLifecycleAction","REPLACEMENT_AUTHORIZED"})assertFalse(s.contains(x));}
 private static BuyReplacementSpreadEligibilityEvaluator evaluator(){return new BuyReplacementSpreadEligibilityEvaluator();} private static BuyReplacementSellPriceCandidateSet set(){return BuyReplacementSellPriceCandidateComposerTest.setForCompanionTests();}
}
