package com.flippingfriend.companion;
import java.util.HashMap; import org.junit.Test; import static org.junit.Assert.*;
public class BuyReplacementQuantityDurationCalibrationInputContextComposerTest {
 @Test public void enabledLearningBindsItemMultiplierAndPreservesEvidence(){BuyReplacementQuantityRoundTripCompletionEvaluationSet s=source();HashMap<Integer,Double> m=new HashMap<>();m.put(s.getItemId(),0.75);FillCalibration c=FillCalibration.forDiagnostics(m,0.9,0.0,2.0);BuyReplacementQuantityDurationCalibrationInputContext r=new BuyReplacementQuantityDurationCalibrationInputContextComposer().compose(s,c,false,1100);assertNotNull(r);assertEquals(0.75,r.getWaitMultiplier(),0.0);assertFalse(r.isLearningDisabled());assertSame(s.getEvaluations(),r.getEvaluations());assertSame(s.getCompleteFillEvaluations(),r.getCompleteFillEvaluations());}
 @Test public void disabledOrMissingCalibrationUsesNeutral(){BuyReplacementQuantityRoundTripCompletionEvaluationSet s=source();HashMap<Integer,Double> m=new HashMap<>();m.put(s.getItemId(),0.5);FillCalibration c=FillCalibration.forDiagnostics(m,0.5,0.0,2.0);BuyReplacementQuantityDurationCalibrationInputContextComposer x=new BuyReplacementQuantityDurationCalibrationInputContextComposer();assertEquals(1.0,x.compose(s,c,true,1100).getWaitMultiplier(),0.0);assertEquals(1.0,x.compose(s,null,false,1100).getWaitMultiplier(),0.0);}
 @Test public void unavailableAndStaleEvidenceFailsClosed(){BuyReplacementQuantityDurationCalibrationInputContextComposer x=new BuyReplacementQuantityDurationCalibrationInputContextComposer();assertNull(x.compose(null,FillCalibration.NEUTRAL,false,1100));assertNull(x.compose(source(),FillCalibration.NEUTRAL,false,1221));}
 @Test public void contractsCarryNoDurationEconomicsSelectionOrAuthorization()throws Exception{for(String f:new String[]{"BuyReplacementQuantityDurationCalibrationInputContext.java","BuyReplacementQuantityDurationCalibrationInputContextComposer.java"}){String s=java.nio.file.Files.readString(java.nio.file.Path.of("src/main/java/com/flippingfriend/companion/"+f));for(String x:new String[]{"correctedHours","expectedSlotHours","unwindLoss","expectedGpPerSlotHour","selected","score","rank","PortfolioCandidate","PolicyDecision","OfferLifecycleAction","REPLACEMENT_AUTHORIZED"})assertFalse(s.contains(x));}}
 static BuyReplacementQuantityDurationCalibrationInputContext contextForCompanionTests(){return new BuyReplacementQuantityDurationCalibrationInputContextComposer().compose(source(),FillCalibration.NEUTRAL,false,1100);} private static BuyReplacementQuantityRoundTripCompletionEvaluationSet source(){return BuyReplacementQuantityRoundTripCompletionEvaluatorTest.quantityRoundTripCompletionEvaluationSetForCompanionTests();}
}
