package com.flippingfriend.companion;
import org.junit.Test; import static org.junit.Assert.*;
public class BuyReplacementRoundTripCompletionEvaluatorTest {
 @Test public void productionFormulaEvaluatesEveryViableCandidateInOrder(){BuyReplacementSellFillViabilityAssessment s=source();BuyReplacementRoundTripCompletionEvaluationSet r=new BuyReplacementRoundTripCompletionEvaluator().evaluate(s,1100);assertNotNull(r);assertEquals(s.getViableCandidates().size(),r.getEvaluations().size());for(int i=0;i<r.getEvaluations().size();i++){BuyReplacementSellFillViableCandidate v=s.getViableCandidates().get(i);BuyReplacementRoundTripCompletionEvaluation e=r.getEvaluations().get(i);assertEquals(v.getBuyProbability()*v.getSellProbability(),e.getCompletionProbability(),0.0);assertEquals(v.getSellOffsetIndex(),e.getSellOffsetIndex());}try{r.getEvaluations().clear();fail("immutable");}catch(UnsupportedOperationException expected){}}
 @Test public void unavailableNonviableAndStaleEvidenceFailClosed(){BuyReplacementRoundTripCompletionEvaluator e=new BuyReplacementRoundTripCompletionEvaluator();assertNull(e.evaluate(null,1100));assertNull(e.evaluate(source(),1221));}
 @Test public void contractsCarryNoDurationEconomicsRankingSelectionOrAuthorization()throws Exception{for(String f:new String[]{"BuyReplacementRoundTripCompletionEvaluation.java","BuyReplacementRoundTripCompletionEvaluationSet.java"}){String s=java.nio.file.Files.readString(java.nio.file.Path.of("src/main/java/com/flippingfriend/companion/"+f));for(String x:new String[]{"correctedHours","expectedSlotHours","expectedProfit","unwindLoss","worstLoss","kelly","selected","score","rank","PortfolioCandidate","PolicyDecision","OfferLifecycleAction","REPLACEMENT_AUTHORIZED"})assertFalse(s.contains(x));}}
 static BuyReplacementRoundTripCompletionEvaluationSet evaluationSetForCompanionTests(){return new BuyReplacementRoundTripCompletionEvaluator().evaluate(source(),1100);}
 private static BuyReplacementSellFillViabilityAssessment source(){return BuyReplacementSellFillViabilityEvaluatorTest.viableAssessmentForCompanionTests();}
}
