package com.flippingfriend.companion;
import com.flippingfriend.model.TaxCalculator; import java.lang.reflect.Method; import java.lang.reflect.Modifier; import java.util.ArrayList; import java.util.Collections; import java.util.List; import org.junit.Test; import static org.junit.Assert.*;
public class BuyReplacementQuantityExpectedGpPerSlotHourEvaluatorTest {
 private final TaxCalculator tax=new TaxCalculator(); private final BuyReplacementQuantityExpectedGpPerSlotHourEvaluator evaluator=new BuyReplacementQuantityExpectedGpPerSlotHourEvaluator(tax);
 @Test public void appliesProductionRateToEveryQuantityAndPreservesEveryGetter()throws Exception{BuyReplacementQuantityKellyFractionEvaluationSet s=source();BuyReplacementQuantityExpectedGpPerSlotHourEvaluationSet r=evaluator.evaluate(s,1100);assertNotNull(r);assertSame(s,r.getSource());assertSame(s.getEvaluations(),r.getKellyFractionEvaluations());assertEquals(s.getEvaluatedAt(),r.getKellyFractionEvaluatedAt());assertEquals(1100,r.getEvaluatedAt());for(Method g:s.getClass().getDeclaredMethods()){if(g.getParameterCount()!=0||g.getName().equals("getSource")||g.getName().equals("getEvaluations")||g.getName().equals("getEvaluatedAt"))continue;Object a=g.invoke(s),b=r.getClass().getDeclaredMethod(g.getName()).invoke(r);if(a instanceof double[])assertArrayEquals((double[])a,(double[])b,0);else assertEquals(a,b);}for(int i=0;i<r.getEvaluations().size();i++){BuyReplacementQuantityKellyFractionEvaluation a=s.getEvaluations().get(i);BuyReplacementQuantityExpectedGpPerSlotHourEvaluation e=r.getEvaluations().get(i);assertSame(a,e.getSource());assertEquals(production(a),e.getQuantityExpectedGpPerSlotHour(),0);assertEquals(a.getQuantity(),e.getQuantity());assertEquals(a.getQuantityKellyFraction(),e.getQuantityKellyFraction(),0);}}
 @Test public void arithmeticIsExactDivisionAndPreservesNegativeRates(){for(double profit:new double[]{-100,-1,0,1,100})for(double hours:new double[]{1.0/60.0,0.5,4})assertEquals(profit/hours,BuyReplacementQuantityExpectedGpPerSlotHourEvaluator.expectedGpPerSlotHour(profit,hours),0);TaxCalculator negative=new TaxCalculator(){@Override public long netMarginPerItem(int i,int b,int s){return -5;}@Override public long netProfit(int i,int b,int s,int q){return -5L*q;}};BuyReplacementQuantityExpectedProfitEvaluationSet p=new BuyReplacementQuantityExpectedProfitEvaluator(negative).evaluate(BuyReplacementQuantityUnwindLossEvaluatorTest.evaluationSetForCompanionTests(),1100);BuyReplacementQuantityWorstLossInputContext c=new BuyReplacementQuantityWorstLossInputContextComposer(negative).compose(p,1100);BuyReplacementQuantityWorstLossEvaluationSet w=new BuyReplacementQuantityWorstLossEvaluator(negative).evaluate(c,1100);BuyReplacementQuantityKellySizingInputContext k=new BuyReplacementQuantityKellySizingInputContextComposer(negative).compose(w,1100);BuyReplacementQuantityKellyFractionEvaluationSet s=new BuyReplacementQuantityKellyFractionEvaluator(negative).evaluate(k,1100);BuyReplacementQuantityExpectedGpPerSlotHourEvaluationSet r=new BuyReplacementQuantityExpectedGpPerSlotHourEvaluator(negative).evaluate(s,1100);assertNotNull(r);assertTrue(r.getEvaluations().get(0).getQuantityExpectedGpPerSlotHour()<0);}
 @Test public void inclusiveFreshnessAndUnavailableAuthorityFailClosed(){assertNotNull(evaluator.evaluate(source(),1220));assertNull(evaluator.evaluate(source(),1221));assertNull(evaluator.evaluate(source(),1099));assertNull(evaluator.evaluate(source(),Long.MAX_VALUE));assertNull(evaluator.evaluate(null,1100));assertNull(new BuyReplacementQuantityExpectedGpPerSlotHourEvaluator(null).evaluate(source(),1100));}
 @Test public void reorderedNullEmptyForeignAndAlteredEvidenceFailClosed(){BuyReplacementQuantityKellyFractionEvaluationSet s=source();List<BuyReplacementQuantityKellyFractionEvaluation> list=new ArrayList<>(s.getEvaluations());assertTrue(list.size()>1);Collections.reverse(list);assertBad(s,list);list=new ArrayList<>(s.getEvaluations());list.set(0,null);assertBad(s,list);list=new ArrayList<>(s.getEvaluations());list.set(0,source().getEvaluations().get(0));assertBad(s,list);BuyReplacementQuantityKellyFractionEvaluation e=s.getEvaluations().get(0);list=new ArrayList<>(s.getEvaluations());list.set(0,new BuyReplacementQuantityKellyFractionEvaluation(e.getSource(),e.getQuantityKellyFraction()+0.01));assertBad(s,list);assertBad(s,Collections.emptyList());}
 @Test public void alteredProfitOrSlotHoursFailClosed(){BuyReplacementQuantityKellyFractionEvaluationSet s=source();BuyReplacementQuantityKellyFractionEvaluation e=s.getEvaluations().get(0);BuyReplacementQuantityKellySizingInput input=e.getSource();for(double profit:new double[]{Double.NaN,Double.POSITIVE_INFINITY,input.getQuantityExpectedProfit()+1})assertBadFirst(s,rebuild(e,input,profit,input.getExpectedSlotHours()));assertFalse(Double.isFinite(BuyReplacementQuantityExpectedGpPerSlotHourEvaluator.expectedGpPerSlotHour(1,0)));}
 @Test public void oneMinuteSlotFloorProducesFiniteProductionRate(){BuyReplacementQuantityKellyFractionEvaluationSet s=source();BuyReplacementQuantityKellyFractionEvaluation e=s.getEvaluations().get(0);assertTrue(e.getExpectedSlotHours()>=1.0/60.0);assertTrue(Double.isFinite(evaluator.evaluate(s,1100).getEvaluations().get(0).getQuantityExpectedGpPerSlotHour()));}
 @Test public void defensiveImmutableAndDeterministic(){BuyReplacementQuantityKellyFractionEvaluationSet s=source();BuyReplacementQuantityExpectedGpPerSlotHourEvaluationSet r=evaluator.evaluate(s,1100);List<BuyReplacementQuantityExpectedGpPerSlotHourEvaluation> copy=new ArrayList<>(r.getEvaluations());BuyReplacementQuantityExpectedGpPerSlotHourEvaluationSet d=new BuyReplacementQuantityExpectedGpPerSlotHourEvaluationSet(s,copy,1100);copy.clear();assertEquals(r.getEvaluations().size(),d.getEvaluations().size());try{r.getEvaluations().clear();fail("immutable");}catch(UnsupportedOperationException expected){}assertEquals(r.getEvaluations().get(0).getQuantityExpectedGpPerSlotHour(),evaluator.evaluate(s,1100).getEvaluations().get(0).getQuantityExpectedGpPerSlotHour(),0);}
 @Test public void contractsRemainPackagePrivateWithoutCandidateRankingOrAuthority()throws Exception{for(Class<?> c:new Class<?>[]{BuyReplacementQuantityExpectedGpPerSlotHourEvaluation.class,BuyReplacementQuantityExpectedGpPerSlotHourEvaluationSet.class,BuyReplacementQuantityExpectedGpPerSlotHourEvaluator.class}){assertFalse(Modifier.isPublic(c.getModifiers()));String x=java.nio.file.Files.readString(java.nio.file.Path.of("src/main/java/com/flippingfriend/companion/"+c.getSimpleName()+".java"));for(String forbidden:new String[]{"new PortfolioCandidate","PortfolioOptimizer","PolicyDecision","OfferLifecycleAction","REPLACEMENT_AUTHORIZED","SqliteStore","schedule","selected","rank","Comparator"})assertFalse(forbidden,x.contains(forbidden));}}
 static BuyReplacementQuantityExpectedGpPerSlotHourEvaluationSet evaluationSetForCompanionTests(){return new BuyReplacementQuantityExpectedGpPerSlotHourEvaluator(new TaxCalculator()).evaluate(source(),1100);}
 private static BuyReplacementQuantityKellyFractionEvaluationSet source(){return BuyReplacementQuantityKellyFractionEvaluatorTest.evaluationSetForCompanionTests();}
 private void assertBad(BuyReplacementQuantityKellyFractionEvaluationSet s,List<BuyReplacementQuantityKellyFractionEvaluation> list){assertNull(evaluator.evaluate(new BuyReplacementQuantityKellyFractionEvaluationSet(s.getSource(),list,1100),1100));}
 private void assertBadFirst(BuyReplacementQuantityKellyFractionEvaluationSet s,BuyReplacementQuantityKellyFractionEvaluation bad){List<BuyReplacementQuantityKellyFractionEvaluation> list=new ArrayList<>(s.getEvaluations());list.set(0,bad);assertBad(s,list);}
 private static BuyReplacementQuantityKellyFractionEvaluation rebuild(BuyReplacementQuantityKellyFractionEvaluation e,BuyReplacementQuantityKellySizingInput input,double profit,double hours){BuyReplacementQuantityWorstLossEvaluation w=input.getSource();BuyReplacementQuantityExpectedProfitEvaluation p=w.getSource();BuyReplacementQuantityExpectedProfitEvaluation changed=new BuyReplacementQuantityExpectedProfitEvaluation(p.getSource(),p.getCompletedSaleNetProfit(),p.getCompletedProbability(),p.getStrandedProbability(),profit);BuyReplacementQuantityWorstLossEvaluation changedW=new BuyReplacementQuantityWorstLossEvaluation(changed,w.getLossCutPct(),w.getQuantityWorstLoss());BuyReplacementQuantityKellySizingInput changedI=new BuyReplacementQuantityKellySizingInput(changedW,input.getQuantityNetProfit(),input.getQuantityUnwindLoss(),input.getQuantityWorstLoss(),input.getCompletionProbability(),input.getPayoffOdds());return new BuyReplacementQuantityKellyFractionEvaluation(changedI,e.getQuantityKellyFraction());}
 private static double production(BuyReplacementQuantityKellyFractionEvaluation e){return e.getQuantityExpectedProfit()/e.getExpectedSlotHours();}
}
