package com.flippingfriend.companion;
import com.flippingfriend.model.RiskAppetite; import org.junit.Test; import static org.junit.Assert.*;
public class BuyReplacementWorstLossInputContextComposerTest {
 @Test public void bindsProductionAppetiteLossCutAndPreservesOrderedEvidence(){BuyReplacementExpectedProfitEvaluationSet s=source();BuyReplacementWorstLossInputContext r=new BuyReplacementWorstLossInputContextComposer().compose(s,1100);assertNotNull(r);assertEquals(RiskAppetite.forName(s.getAppetiteName()).getLossCutPct(),r.getLossCutPct(),0.0);assertSame(s.getEvaluations(),r.getEvaluations());assertEquals(s.getEvaluatedAt(),r.getExpectedProfitEvaluatedAt());}
 @Test public void unavailableAndStaleInputsFailClosed(){BuyReplacementWorstLossInputContextComposer c=new BuyReplacementWorstLossInputContextComposer();assertNull(c.compose(null,1100));assertNull(c.compose(source(),1221));}
 @Test public void contractsCarryNoWorstLossSizingThroughputRankingSelectionOrAuthorization()throws Exception{for(String f:new String[]{"BuyReplacementWorstLossInputContext.java","BuyReplacementWorstLossInputContextComposer.java"}){String x=java.nio.file.Files.readString(java.nio.file.Path.of("src/main/java/com/flippingfriend/companion/"+f));for(String forbidden:new String[]{"getWorstLoss","worstLoss=","kelly","expectedGpPerSlotHour","positionSize","selected","score","rank","PortfolioCandidate","PolicyDecision","OfferLifecycleAction","REPLACEMENT_AUTHORIZED"})assertFalse(x.contains(forbidden));}}
 static BuyReplacementWorstLossInputContext evaluationContextForCompanionTests(){return contextForCompanionTests();}
 static BuyReplacementWorstLossInputContext contextForCompanionTests(){return new BuyReplacementWorstLossInputContextComposer().compose(source(),1100);} private static BuyReplacementExpectedProfitEvaluationSet source(){return BuyReplacementExpectedProfitEvaluatorTest.worstLossSourceForCompanionTests();}
}
