package com.flippingfriend.companion;
import com.flippingfriend.model.TaxCalculator; import org.junit.Test; import static org.junit.Assert.*;
public class BuyReplacementNetMarginEvaluatorTest {
 @Test public void evaluatesEveryPositiveSpreadWithoutFilteringLosses(){BuyReplacementNetMarginEvaluationSet r=evaluator().evaluate(spread(),new TaxCalculator(),1001);assertNotNull(r);assertEquals(4,r.getEvaluations().size());long[] margins={-1,-2,-4,-7};for(int i=0;i<4;i++){BuyReplacementNetMarginEvaluation e=r.getEvaluations().get(i);assertEquals(10,e.getTaxPerItem());assertEquals(margins[i],e.getNetMarginPerItem());assertEquals(50,e.getTotalTax());assertEquals(margins[i]*5,e.getTotalNetMargin());assertEquals(i,e.getSellOffsetIndex());}}
 @Test public void preservesUpstreamViewsAndIsImmutable(){BuyReplacementNetMarginEvaluationSet r=evaluator().evaluate(spread(),new TaxCalculator(),1001);assertEquals(4,r.getCandidates().size());assertEquals(4,r.getPositiveSpreadCandidates().size());try{r.getEvaluations().clear();fail("immutable");}catch(UnsupportedOperationException expected){}}
 @Test public void unavailableTaxAndIneligibleEvidenceFailClosed(){assertNull(evaluator().evaluate(null,new TaxCalculator(),1001));assertNull(evaluator().evaluate(spread(),null,1001));assertNull(evaluator().evaluate(spread(),new TaxCalculator(),999));}
 @Test public void contractsCarryNoFilteringRankingSelectionOrAuthorization()throws Exception{String s=java.nio.file.Files.readString(java.nio.file.Path.of("src/main/java/com/flippingfriend/companion/BuyReplacementNetMarginEvaluationSet.java"));for(String x:new String[]{"profitable","selected","preferred","winner","score","rank","PolicyDecision","OfferLifecycleAction","REPLACEMENT_AUTHORIZED"})assertFalse(s.contains(x));}
 static BuyReplacementNetMarginEvaluationSet setForCompanionTests(TaxCalculator tax){return evaluator().evaluate(spread(),tax,1001);}
 private static BuyReplacementNetMarginEvaluator evaluator(){return new BuyReplacementNetMarginEvaluator();} private static BuyReplacementSpreadEligibilityAssessment spread(){return BuyReplacementSpreadEligibilityEvaluatorTest.eligibleForCompanionTests();}
}
