package com.flippingfriend.companion;
import java.util.HashMap; import org.junit.Test; import static org.junit.Assert.*;
public class BuyReplacementDurationCalibrationInputContextComposerTest {
 @Test public void enabledLearningBindsItemMultiplierAndPreservesEvidence(){BuyReplacementRoundTripCompletionEvaluationSet s=source();HashMap<Integer,Double> m=new HashMap<>();m.put(s.getItemId(),0.75);FillCalibration c=FillCalibration.forDiagnostics(m,0.9,0.0,2.0);BuyReplacementDurationCalibrationInputContext r=new BuyReplacementDurationCalibrationInputContextComposer().compose(s,c,false,1100);assertNotNull(r);assertEquals(0.75,r.getWaitMultiplier(),0.0);assertFalse(r.isLearningDisabled());assertSame(s.getEvaluations(),r.getEvaluations());}
 @Test public void disabledOrMissingCalibrationUsesNeutral(){BuyReplacementRoundTripCompletionEvaluationSet s=source();HashMap<Integer,Double> m=new HashMap<>();m.put(s.getItemId(),0.5);FillCalibration c=FillCalibration.forDiagnostics(m,0.5,0.0,2.0);BuyReplacementDurationCalibrationInputContextComposer x=new BuyReplacementDurationCalibrationInputContextComposer();assertEquals(1.0,x.compose(s,c,true,1100).getWaitMultiplier(),0.0);assertEquals(1.0,x.compose(s,null,false,1100).getWaitMultiplier(),0.0);}
 @Test public void unavailableAndStaleEvidenceFailsClosed(){BuyReplacementDurationCalibrationInputContextComposer x=new BuyReplacementDurationCalibrationInputContextComposer();assertNull(x.compose(null,FillCalibration.NEUTRAL,false,1100));assertNull(x.compose(source(),FillCalibration.NEUTRAL,false,1221));}
 @Test public void contractsCarryNoDurationEconomicsSelectionOrAuthorization()throws Exception{for(String f:new String[]{"BuyReplacementDurationCalibrationInputContext.java","BuyReplacementDurationCalibrationInputContextComposer.java"}){String s=java.nio.file.Files.readString(java.nio.file.Path.of("src/main/java/com/flippingfriend/companion/"+f));for(String x:new String[]{"correctedHours","expectedSlotHours","expectedProfit","unwindLoss","worstLoss","kelly","selected","score","rank","PortfolioCandidate","PolicyDecision","OfferLifecycleAction","REPLACEMENT_AUTHORIZED"})assertFalse(s.contains(x));}}
 private static BuyReplacementRoundTripCompletionEvaluationSet source(){return BuyReplacementRoundTripCompletionEvaluatorTest.evaluationSetForCompanionTests();}
}
