package com.flippingfriend.companion;
import java.util.ArrayList; import java.util.List; import org.junit.Test; import static org.junit.Assert.*;
public class BuyReplacementSellFillViabilityEvaluatorTest {
 @Test public void plausibilityDerivesOrderedViableView(){BuyReplacementSellFillViabilityAssessment r=new BuyReplacementSellFillViabilityEvaluator().evaluate(source(false),1100);assertNotNull(r);assertEquals(BuyReplacementSellFillViabilityOutcome.VIABLE,r.getOutcome());assertEquals(2,r.getEvaluations().size());assertEquals(1,r.getViableCandidates().size());assertEquals(r.getEvaluations().get(1).getSellOffsetIndex(),r.getViableCandidates().get(0).getSellOffsetIndex());try{r.getViableCandidates().clear();fail("immutable");}catch(UnsupportedOperationException expected){}}
 @Test public void allNeverFillEvidenceIsNotViable(){BuyReplacementSellFillViabilityAssessment r=new BuyReplacementSellFillViabilityEvaluator().evaluate(source(true),1100);assertNotNull(r);assertEquals(BuyReplacementSellFillViabilityOutcome.NOT_VIABLE,r.getOutcome());assertEquals(2,r.getEvaluations().size());assertTrue(r.getViableCandidates().isEmpty());}
 @Test public void staleMissingAndMalformedEvidenceFailClosed(){BuyReplacementSellFillViabilityEvaluator e=new BuyReplacementSellFillViabilityEvaluator();assertNull(e.evaluate(null,1100));assertNull(e.evaluate(source(false),1221));BuyReplacementSellFillEvaluationSet b=BuyReplacementSellFillEvaluatorTest.evaluationSetForCompanionTests();List<BuyReplacementSellFillEvaluation> bad=new ArrayList<>(b.getEvaluations());BuyReplacementPositiveNetMarginCandidate c=b.getCandidates().get(0);bad.set(0,new BuyReplacementSellFillEvaluation(c,Double.NaN,1,1,1));assertNull(e.evaluate(new BuyReplacementSellFillEvaluationSet(context(),bad,1100),1100));}
 @Test public void contractsCarryNoModelEconomicsSelectionOrAuthorization()throws Exception{for(String f:new String[]{"BuyReplacementSellFillViableCandidate.java","BuyReplacementSellFillViabilityAssessment.java"}){String s=java.nio.file.Files.readString(java.nio.file.Path.of("src/main/java/com/flippingfriend/companion/"+f));for(String x:new String[]{"FillModel","FillCurve","combined","expectedValue","unwind","selected","score","rank","PolicyDecision","OfferLifecycleAction","REPLACEMENT_AUTHORIZED"})assertFalse(s.contains(x));}}
 private static BuyReplacementSellFillEvaluationSet source(boolean allNever){BuyReplacementSellFillEvaluationSet b=BuyReplacementSellFillEvaluatorTest.evaluationSetForCompanionTests();List<BuyReplacementSellFillEvaluation> v=new ArrayList<>();for(int i=0;i<b.getCandidates().size();i++){BuyReplacementPositiveNetMarginCandidate c=b.getCandidates().get(i);boolean never=allNever||i==0;v.add(new BuyReplacementSellFillEvaluation(c,never?0:0.6,never?Double.POSITIVE_INFINITY:1.2,never?0:100,never?Double.POSITIVE_INFINITY:0.2));}return new BuyReplacementSellFillEvaluationSet(context(),v,1100);} private static BuyReplacementSellFillInputContext context(){return BuyReplacementSellFillInputContextComposerTest.contextForCompanionTests();}
}
