package com.flippingfriend.companion;
import org.junit.Test; import static org.junit.Assert.*;
public class BuyReplacementKellySizingInputContextComposerTest {
 @Test public void bindsExactProductionKellyInputsAndConstantsWithoutSizing(){BuyReplacementWorstLossEvaluationSet s=source();BuyReplacementKellySizingInputContext r=new BuyReplacementKellySizingInputContextComposer().compose(s,1100);assertNotNull(r);assertEquals(0.35,r.getKellyShare(),0.0);assertEquals(0.1,r.getMinimumKellyFraction(),0.0);assertArrayEquals(new double[]{0.5,1.0,2.0,4.0,8.0},r.getSizeGrid(),0.0);assertEquals(s.getEvaluations().size(),r.getInputs().size());for(int i=0;i<r.getInputs().size();i++){BuyReplacementWorstLossEvaluation e=s.getEvaluations().get(i);BuyReplacementKellySizingInput x=r.getInputs().get(i);assertEquals(e.getTotalNetMargin(),x.getFullNetProfit());assertEquals(e.getTotalUnwindLoss(),x.getFullUnwindLoss());assertEquals(e.getCompletionProbability(),x.getCompletionProbability(),0.0);double b=e.getTotalUnwindLoss()>0?(double)e.getTotalNetMargin()/e.getTotalUnwindLoss():e.getTotalNetMargin();assertEquals(b,x.getPayoffOdds(),0.0);}double[] grid=r.getSizeGrid();grid[0]=99;assertEquals(0.5,r.getSizeGrid()[0],0.0);}
 @Test public void unavailableAndStaleInputsFailClosed(){BuyReplacementKellySizingInputContextComposer c=new BuyReplacementKellySizingInputContextComposer();assertNull(c.compose(null,1100));assertNull(c.compose(source(),1221));}
 @Test public void contractsCarryNoFractionQuantityRankingSelectionOrAuthorization()throws Exception{for(String f:new String[]{"BuyReplacementKellySizingInput.java","BuyReplacementKellySizingInputContext.java"}){String x=java.nio.file.Files.readString(java.nio.file.Path.of("src/main/java/com/flippingfriend/companion/"+f));for(String forbidden:new String[]{"kellyFraction(","Math.round","expectedGpPerSlotHour","selected","score","rank","PortfolioCandidate","PolicyDecision","OfferLifecycleAction","REPLACEMENT_AUTHORIZED"})assertFalse(x.contains(forbidden));}}
 static BuyReplacementKellySizingInputContext kellyEvaluationContextForCompanionTests(){return contextForCompanionTests();}
 static BuyReplacementKellySizingInputContext contextForCompanionTests(){return new BuyReplacementKellySizingInputContextComposer().compose(source(),1100);} private static BuyReplacementWorstLossEvaluationSet source(){return BuyReplacementWorstLossEvaluatorTest.kellySourceForCompanionTests();}
}
